import { IAnimal } from "../../mockData/animals";
import { AlpacaIcon, AntIcon, BeeIcon, BirdIcon, ButterflyIcon, CaterpillarIcon, CatIcon, ChameleonIcon, ChickIcon, ClownFishIcon, CorgiIcon, CowIcon, CrabIcon, CraneIcon, CrocodileIcon, DeerIcon, DefaultIcon, DinosaurIcon, DogIcon, DolphinIcon, DonkeyIcon, DragonflyIcon, DuckIcon, EagleIcon, ElephantIcon, FireflyIcon, FishIcon, FlamingoIcon, FoxIcon, GeckoIcon, GiraffeIcon, GoatIcon, GorillaIcon, GrasshopperIcon, HamsterIcon, HedgehogIcon, HippoIcon, HorseIcon, JellyfishIcon, KangarooIcon, KoalaIcon, LadybugIcon, LionIcon, MantisIcon, MonkeyIcon, MouseIcon, OctopusIcon, OwlIcon, PandaIcon, ParrotIcon, PeacockIcon, PenguinIcon, PigIcon, PolarBearIcon, PufferfishIcon, RabbitIcon, RaccoonIcon, RhinoIcon, RoosterIcon, SeahorseIcon, SealIcon, SharkIcon, SheepIcon, ShrimpIcon, SlothIcon, SnailIcon, SnakeIcon, SquirrelIcon, StarfishIcon, SwanIcon, TigerIcon, TotoroIcon, TurkeyIcon, TurtleIcon, WhaleIcon, WolfIcon, ZebraIcon } from "./icons";

export function AnimalIcon({ animal }: { animal: IAnimal }) {
  // 根据动物类型返回不同的SVG图标
  const iconMap: Record<string, JSX.Element> = {
    小橘猫: <CatIcon color="#F59E0B" />,
    英短蓝猫: <CatIcon color="#6B7280" />,
    布偶猫: <CatIcon color="#D1D5DB" />,
    暹罗猫: <CatIcon color="#D4B896" />,
    波斯猫: <CatIcon color="#F5F5DC" />,
    加菲猫: <CatIcon color="#EA580C" />,
    三花猫: <CatIcon color="#D97706" />,
    奶牛猫: <CatIcon color="#374151" />,
    狮子: <LionIcon />,
    老虎: <TigerIcon />,
    金毛犬: <DogIcon color="#D4A574" />,
    柯基犬: <CorgiIcon />,
    哈士奇: <DogIcon color="#6B7280" />,
    柴犬: <DogIcon color="#EA580C" />,
    萨摩耶: <DogIcon color="#F3F4F6" />,
    泰迪犬: <DogIcon color="#8B4513" />,
    边牧: <DogIcon color="#1F2937" />,
    法斗: <DogIcon color="#D4B896" />,
    狼: <WolfIcon />,
    狐狸: <FoxIcon />,
    垂耳兔: <RabbitIcon color="#E5E7EB" hasLopEars />,
    小白兔: <RabbitIcon color="#FFFFFF" />,
    灰兔兔: <RabbitIcon color="#9CA3AF" />,
    仓鼠球: <HamsterIcon />,
    小松鼠: <SquirrelIcon />,
    花栗鼠: <SquirrelIcon striped />,
    豚鼠: <HamsterIcon color="#D4A574" />,
    龙猫: <TotoroIcon />,
    小老鼠: <MouseIcon />,
    刺猬: <HedgehogIcon />,
    鹦鹉: <ParrotIcon />,
    小黄鸭: <DuckIcon />,
    猫头鹰: <OwlIcon />,
    企鹅: <PenguinIcon />,
    小鸡仔: <ChickIcon />,
    燕子: <BirdIcon color="#1F2937" />,
    麻雀: <BirdIcon color="#92400E" />,
    孔雀: <PeacockIcon />,
    火烈鸟: <FlamingoIcon />,
    天鹅: <SwanIcon />,
    鹦鹉螺: <BirdIcon color="#6B7280" />,
    老鹰: <EagleIcon />,
    仙鹤: <CraneIcon />,
    知更鸟: <BirdIcon color="#EA580C" />,
    蜂鸟: <BirdIcon color="#10B981" />,
    小金鱼: <FishIcon color="#3B82F6" />,
    小丑鱼: <ClownFishIcon />,
    海豚: <DolphinIcon />,
    鲸鱼: <WhaleIcon />,
    海龟: <TurtleIcon color="#22C55E" />,
    章鱼: <OctopusIcon />,
    水母: <JellyfishIcon />,
    海星: <StarfishIcon />,
    螃蟹: <CrabIcon />,
    虾米: <ShrimpIcon />,
    海马: <SeahorseIcon />,
    鲨鱼: <SharkIcon />,
    海豹: <SealIcon />,
    锦鲤: <FishIcon color="#EF4444" />,
    河豚: <PufferfishIcon />,
    小蜜蜂: <BeeIcon />,
    蝴蝶: <ButterflyIcon />,
    瓢虫: <LadybugIcon />,
    蜻蜓: <DragonflyIcon />,
    萤火虫: <FireflyIcon />,
    蚂蚁: <AntIcon />,
    蚱蜢: <GrasshopperIcon />,
    毛毛虫: <CaterpillarIcon />,
    蜗牛: <SnailIcon />,
    螳螂: <MantisIcon />,
    大熊猫: <PandaIcon />,
    小浣熊: <RaccoonIcon />,
    考拉: <KoalaIcon />,
    树懒: <SlothIcon />,
    长颈鹿: <GiraffeIcon />,
    大象: <ElephantIcon />,
    斑马: <ZebraIcon />,
    河马: <HippoIcon />,
    犀牛: <RhinoIcon />,
    猴子: <MonkeyIcon />,
    大猩猩: <GorillaIcon />,
    袋鼠: <KangarooIcon />,
    麋鹿: <DeerIcon />,
    羊驼: <AlpacaIcon />,
    北极熊: <PolarBearIcon />,
    小蛇蛇: <SnakeIcon />,
    变色龙: <ChameleonIcon />,
    壁虎: <GeckoIcon />,
    乌龟: <TurtleIcon color="#22C55E" />,
    鳄鱼: <CrocodileIcon />,
    蜥蜴: <GeckoIcon />,
    恐龙: <DinosaurIcon />,
    小猪猪: <PigIcon />,
    奶牛: <CowIcon />,
    绵羊: <SheepIcon />,
    山羊: <GoatIcon />,
    小马驹: <HorseIcon />,
    小毛驴: <DonkeyIcon />,
    公鸡: <RoosterIcon />,
    火鸡: <TurkeyIcon />,
  }

  return iconMap[animal.name] || <DefaultIcon color={animal.color} emoji={animal.emoji} />
}
